apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: carritoapm-argo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ValentinGarciaIriart/CarritoAPM.git
    targetRevision: HEAD
    path: k8s
  destination: 
    server: https://kubernetes.default.svc
    namespace: onlyapm

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true